### ISSUE TITLE
사이트 방문하면 항상 보이는 아이콘들이 추가되면 좋겠어요.

### ISSUE THREAD

**Issue by Plush777** [vector-icons/vector-icons#1]
예를 들면, 다음과 같은 아이콘들이요!
당장 기억나는 것들만 적었어요.

- [Eye on (View password enable)](https://www.iconfinder.com/icons/8666618/eye_icon)
- [Eye off(View password disable)](https://www.iconfinder.com/icons/8666649/eye_off_icon)
- [Grid](https://www.iconfinder.com/icons/9041814/grid_squares_icon)
- [Open in new](https://www.iconfinder.com/icons/3669314/in_open_new_ic_icon)
- [Scroll to top](https://www.iconfinder.com/icons/4600835/top_up_upload_icon)
- [Arrow top](https://www.iconfinder.com/icons/4600813/arrow_top_up_icon)
- [Arrow bottom](https://www.iconfinder.com/icons/4781856/arrow_arrows_bottom_direction_down_navigation_up_icon)
- [Arrow left](https://www.iconfinder.com/icons/4829870/arrow_back_left_icon)
- [Arrow right](https://www.iconfinder.com/icons/4781858/arrow_arrows_back_direction_left_navigation_right_icon)
- [Plus](https://www.iconfinder.com/icons/4600814/add_create_new_plus_icon)
- [Minus](https://www.iconfinder.com/icons/211863/minus_round_icon)
- [More column](https://www.iconfinder.com/icons/3844442/dot_menu_more_vertical_icon)
- [More row](https://www.iconfinder.com/icons/211781/more_icon)
- [Close](https://www.iconfinder.com/icons/4115230/cancel_close_delete_icon)
- [Home](https://www.iconfinder.com/icons/392500/estate_home_house_real_icon)
- [information](https://www.iconfinder.com/icons/1108720/about_infor_information_news_icon)
- [Exclamation](https://www.iconfinder.com/icons/3643776/caution_exclamation_mark_round_sign_icon)
- [Question mark](https://www.iconfinder.com/icons/430101/help_question_icon)
- [No image](https://www.vecteezy.com/free-vector/no-image-available)
- [Check (Checkbox)](https://www.iconfinder.com/icons/4630293/alright_check_checkmark_hook_okay_save_saved_icon)
- [Play (Video, Slide)](https://www.veryicon.com/icons/internet--web/truckhome/play-47.html)
- [Pause (Video, Slide)](https://www.veryicon.com/icons/miscellaneous/ios-icon-library/pause-pause.html)

**Comment by MTtankkeo** [comment]
아이콘 제작에 필요한 소중한 자료를 시간을 내어 이슈로 남겨주셔서 감사드립니다요. 😄, 이 은혜를 보답하기 위해 빠른 시간 내에 만들어 보도록 하겠습니다요
